version: '3.7'

networks:
    mynetwork:
        ipam:
            config:
                - subnet: 172.20.0.0/24

volumes:
    mariadb-10.3.16_data:
    mysql-8.0.28_data:
    postgres-13.0-alpine_data:

services:
    mariadb-10.3.16:
        container_name: mariadb
        image: mariadb:10.3.16
        restart: always
        environment:
            MYSQL_DATABASE: test_db
            MYSQL_ROOT_PASSWORD: 123456
            MYSQL_PASSWORD: 123456
            MYSQL_USER: root
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        ports:
            - "3307:3306"
        volumes:
            - mariadb-10.3.16_data:/var/lib/mariadb
        networks:
            mynetwork:
                ipv4_address: 172.20.0.6

    mysql-8.0.28:
        container_name: mysql
        image: mysql:8.0.28
        restart: always
        command: [
            "--default-authentication-plugin=mysql_native_password",
            "--log_bin_trust_function_creators=1",
        ]
        environment:
            MYSQL_ROOT_PASSWORD: 123456
            MYSQL_DATABASE: test_db
            MYSQL_PASSWORD: 123456
            MYSQL_DB: test_db
        ports:
            - "3308:3307"
        volumes:
            - mysql-8.0.28_data:/var/lib/mysql
        networks:
            mynetwork:
                ipv4_address: 172.20.0.7

    postgres-13.0-alpine:
        container_name: postgres
        image: postgres:13.0-alpine
        restart: 'always'
        environment:
            POSTGRES_DB: test_db
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: 123456
        ports:
            - "5433:5432"
        volumes:
            - postgres-13.0-alpine_data:/var/lib/postgresql/data/
        networks:
            mynetwork:
                ipv4_address: 172.20.0.8
